(function(g){var window=this;var i4=function(a){var b={format:a.G,languageCode:a.A,languageName:a.C,displayName:g.uI(a),kind:a.B,name:a.D,id:a.Ia,is_servable:a.K,is_default:a.isDefault,is_translateable:a.H,vss_id:a.F};a.o&&(a=a.o,b.translationLanguage={languageCode:a.languageCode,languageName:a.languageName,languageOriginal:a.o,id:a.id,is_default:a.isDefault});return b},j4=function(a){return a.o?a.o.languageCode:a.A},pDa=function(a,b){var c=new g.tI;
c.A=a.A;c.C=a.C;c.D=a.D;c.B=a.B;c.isDefault=!1;c.H=a.H;c.F=a.F;c.J=a.J;c.o=b;return c},k4=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.TP.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.D=f;this.A=k},l4=function(a,b,c,d,e){g.TP.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.A=[]},n4=function(a){a=void 0===a?{}:a;
var b="_"+m4++;return new l4(0,0x8000000000000,0,b,a)},o4=function(a,b,c,d,e,f,k){var l={};
g.Da(l,b);g.Da(l,a.params);g.Da(l,c);var m={};g.Da(m,b.Jb);a.params.Jb&&g.Da(m,a.params.Jb);g.Da(m,c.Jb);l.Jb=m;g.V.call(this,{I:"div",N:"caption-window",T:{id:"caption-window-"+a.id,dir:1==l.ci?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:l.lang},P:[{I:"span",N:"captions-text"}]});this.F=[];this.ca=!1;this.D=a;this.J=[];this.L=[];this.bb=e;this.Ua=f;this.Qa=k;this.H=null;this.ka=.96*e;this.za=.96*f;this.B=l;this.Ja=c;this.C=this.o["captions-text"];this.Da=null!=this.C.style["box-decoration-break"]||
null!=this.C.style["-webkit-box-decoration-break"];this.ga=d/360*16;this.type=0;this.na=this.ga*qDa(m);a=new g.kG(this.element,!0);g.O(this,a);a.subscribe("dragstart",this.CQ,this);a.subscribe("dragmove",this.BQ,this);a.subscribe("dragend",this.AQ,this);this.wa=this.ra=0;a="";this.B.windowOpacity&&(a=g.Xt(this.B.windowColor),a="rgba("+a[0]+","+a[1]+","+a[2]+","+this.B.windowOpacity+")");b={"background-color":a,display:!1===this.B.isVisible?"none":"","text-align":rDa[this.B.textAlign]};this.Da&&(b["border-radius"]=
a?this.na/8+"px":"");(this.G=this.Qa.o("web_player_vertical_captions")&&(2==this.D.params.ci||3==this.D.params.ci))&&sDa(this,this.element);g.yh(this.element,b);switch(this.B.kh){case 0:case 1:case 2:g.T(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.T(this.element,"ytp-caption-window-bottom")}},sDa=function(a,b){var c="vertical-rl";
1==a.B.wx&&(c="vertical-lr");g.Jd&&(c="vertical-lr"==c?"tb-lr":"tb-rl");g.yh(b,"-o-writing-mode",c);g.yh(b,"-webkit-writing-mode",c);g.yh(b,"writing-mode",c);g.yh(b,"text-orientation","upright");3==a.D.params.ci&&(g.yh(b,"text-orientation",""),g.yh(b,"transform","rotate(180deg)"))},qDa=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0==a.offset||2==a.offset)b*=.8;return b},p4=function(a,b){var c={},d=b.background?b.background:a.B.Jb.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.B.Jb.backgroundOpacity;d=g.Xt(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Da&&(c["box-decoration-break"]="clone",c["border-radius"]=a.na/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.ga*qDa(b)+"px";d=1;e=b.color||a.B.Jb.color;if(b.color||null!=b.textOpacity)e=g.Xt(e),d=null==b.textOpacity?a.B.Jb.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",
c.color=e,c.fill=e;var f=b.charEdgeStyle;0==f&&(f=null);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";b.Rz&&(k=e=b.Rz);var l=a.ga/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),t=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=t;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+
n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.XE()?
'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.B.Jb.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7==b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.Cf&&(c["font-style"]="italic");
b.underline&&(c["text-decoration"]="underline");b.Fp&&(c.visibility="hidden");return c},tDa=function(a,b,c){a.ca=a.ca||!!c;
var d={};g.Da(d,a.B.Jb);g.Da(d,c||b.A);g.Da(d,a.Ja.Jb);c=a.J[0];if(c&&d.background==c.background&&d.backgroundOpacity==c.backgroundOpacity&&!!d.Fp==!!c.Fp&&d.charEdgeStyle==c.charEdgeStyle){var e;for(e=0;e<a.J.length;e++)if(g.ac(d,a.J[e])){var f=a.L[e];break}if(!f){e={};for(var k in d)d[k]!=c[k]&&(e[k]=d[k]);f=g.Rd("SPAN");g.yh(f,p4(a,e));a.L[0].appendChild(f);e=1}a.L.length=e;a.J.length=e}else a.L.length=0,a.J.length=0,f=g.Rd("SPAN"),g.yh(f,p4(a,d)),a.C.appendChild(f);k=!d.Fp;e=(c=g.v(b.text))?b.text.split("\n"):
[b.text];for(var l=0;l<e.length;l++){var m=e[l];if(0<l||0==a.F.length||!b.D){if(0<l||0!=a.F.length){var n=g.Rd("BR");f.appendChild(n)}k&&a.Fl(f)}m&&(k?a.H:f).appendChild(c?g.Sd(m):m)}if(!c)for(k=b.text.querySelectorAll("RT".toString()),c=0;c<k.length;c++)g.yh(k[c],p4(a,d)),g.yh(k[c],"font-size","50%");a.J.push(d);a.L.push(f);a.F.push(b)},uDa=function(){},r4=function(){this.C=this.A=this.mode=this.B=0;
this.D=new q4(this);this.F=new q4(this);this.o=[];this.clear()},wDa=function(a,b,c){if(255==a&&255==b||!a&&!b)return{Ao:a,
Bo:b,result:0};a=vDa[a];b=vDa[b];if(a&128){if(!(b&128)&&0!=c.o&&c.A==b)return{Ao:a,Bo:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Ao:a,Bo:b,result:2};return{Ao:a,Bo:b,result:3}},yDa=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.C&&a.reset(),a.D.o.clear(),a.F.o.clear()):(a.C=0,xDa(a.D,b,c,d))},zDa=function(a,b){a.o.sort(function(a,b){var c=a.time-b.time;
return 0==c?a.order-b.order:c});
for(var c=0;c<a.o.length;c++){var d=a.o[c];a.A=d.time;0==d.type?yDa(a,d.Mz,d.Nz,b):1==d.type&&a.B&496&&xDa(a.F,d.Mz,d.Nz,b)}a.o.length=0},s4=function(){this.o=0},t4=function(){this.A=this.B=this.o=0},u4=function(){this.timestamp=this.Ne=0},v4=function(a){this.B=[];
for(var b=0;15>=b;b++){this.B[b]=[];for(var c=0;32>=c;c++)this.B[b][c]=new u4}this.o=this.A=this.row=0;this.style=new s4;this.D=a;this.C=0},w4=function(a,b){if(3==a.style.o){for(var c=0,d=0,e=a.D.A+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var t=a.B[m][p];
if(0!=t.Ne){0==c&&(c=m,d=p);n=String.fromCharCode(t.Ne);var w=t.timestamp;w<e&&(e=w);t.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0==t.Ne||32==p)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.D(c,d,e,l,f)}else for(d=c=0,f=e=a.D.A+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(p=a.B[k][m],t=p.Ne,0!=t&&(0==c&&(c=k,d=m),n=String.fromCharCode(t),w=p.timestamp,w<=e&&(e=w),l+=n,p.reset()),32==m||0==t)l&&b.D(c,d,e,f,l),e=f,l="",d=c=0},EDa=function(a,b){switch(a){case 0:return ADa[(b&127)-32];
case 1:return BDa[b&15];case 2:return CDa[b&31];case 3:return DDa[b&31]}return 0},x4=function(a){return a.B[a.row][a.A]},y4=function(a,b,c){2<=b&&1<a.A&&(--a.A,x4(a).Ne=0);
var d=x4(a);d.timestamp=a.D.A+0;d.Ne=EDa(b,c);32>a.A&&a.A++},FDa=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.B[b+e][f].To(a.B[c+e][f])},z4=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.B[b+d][e].reset()},A4=function(a){a.row=0<a.o?a.o:1;
a.A=1;z4(a,0,15)},B4=function(a){this.C=a;
this.D=0;this.style=new s4;this.F=new v4(a);this.G=new v4(a);this.H=new v4(a);this.A=this.F;this.B=this.G;this.o=this.A},C4=function(a,b,c){var d=a.A,e=!1;
switch(a.style.get()){case 4:if(0<d.o)break;case 1:case 2:w4(d,c),A4(a.A),A4(a.B),d.row=15,d.o=b,e=!0}a.style.set(3);a.o=d;a.o.style=a.style;a.C.mode=1<<d.C;e?d.A=1:d.o!=b&&(d.o>b?(w4(d,c),z4(d,d.row-d.o,b)):d.row<b&&(b=d.o),d.o=b)},GDa=function(a){a.style.set(1);
a.o=a.B;a.o.o=0;a.o.style=a.style;a.C.mode=1<<a.o.C},HDa=function(a){a.style.set(4);
a.o=a.H;a.o.style=a.style;a.C.mode=1<<a.o.C},q4=function(a){this.A=a;
this.o=new t4;this.D=0;this.B=new B4(a);this.F=new B4(a);this.C=this.B},xDa=function(a,b,c,d){a.o.update();
b=wDa(b,c,a.o);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Ao;c=b.Bo;if(32<=e||!e)a.A.mode&a.A.B&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.C.o,b&96&&y4(a,0,b),c&96&&y4(a,0,c),0!=b&&0!=c&&3==a.style.o&&w4(a,d));else if(e&16)a:if(!a.o.matches(e,c)&&(b=a.o,b.B=e,b.A=c,b.o=2,b=e&8?a.F:a.B,a.C=b,a.A.mode=1<<(a.D<<2)+(b.D<<1)+(4==b.style.o?1:0),(a.A.mode|1<<(a.D<<2)+(b.D<<1)+(4!=b.style.o?1:0))&a.A.B))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*((c&14)>>1):
0;c=b.o;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!=c.row){if(d<c.o&&(d=c.o,d==c.row))break;var f=1+c.row-c.o,k=1+d-c.o;FDa(c,k,f,c.o);b=f;e=c.o;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));z4(c,b,e)}}c.row=d;c.A=a+1}else switch(e&7){case 1:switch(c&112){case 32:y4(b.o,0,32);break a;case 48:57==c?(b=b.o,x4(b).Ne=0,32>b.A&&b.A++):y4(b.o,1,c&15)}break;case 2:c&32&&y4(b.o,2,c&31);break;case 3:c&32&&y4(b.o,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:GDa(b);break;
case 33:b=b.o;1<b.A&&(--b.A,x4(b).Ne=0);break;case 36:b=b.o;d=x4(b);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(b.B[a][c]==d){for(;32>=c;c++)b.B[a][c].reset();break}break;case 37:C4(b,2,d);break;case 38:C4(b,3,d);break;case 39:C4(b,4,d);break;case 40:y4(b.o,0,32);break;case 41:b.style.set(2);b.o=b.A;b.o.o=0;b.o.style=b.style;b.C.mode=1<<b.o.C;break;case 42:d=b.H;d.o=15;d.style.set(4);A4(d);HDa(b);break;case 43:HDa(b);break;case 44:a=b.A;switch(b.style.get()){case 1:case 2:case 3:w4(a,d)}z4(a,0,15);break;
case 45:b:{a=b.o;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.A=1;break b}case 3:}2>a.o&&(a.o=2,a.row<a.o&&(a.row=a.o));b=a.row-a.o+1;w4(a,d);FDa(a,b,b+1,a.o-1);z4(a,a.row,1)}break;case 46:z4(b.B,0,15);break;case 47:w4(b.A,d);d=b.B;a=b.C.A+0;for(c=1;15>=c;++c)for(e=1;32>=e;++e)d.B[c][e].timestamp=a;d=b.B;b.B=b.A;b.A=d;GDa(b)}break;case 7:switch(c){case 33:case 34:case 35:b=b.o,32<(b.A+=c&3)&&(b.A=32)}}},D4=function(a){g.M.apply(this,arguments)},E4=function(a){D4.call(this);
this.A=a;this.o=null},IDa=function(a,b,c,d,e,f,k,l){switch(f.tagName){case "b":k.bold=!0;
break;case "i":k.Cf=!0;break;case "u":k.underline=!0;break;case "font":var m=f.getAttribute("color");F4.test(m);k.color=m}for(m=0;m<f.childNodes.length;m++){var n=f.childNodes[m];if(3==n.nodeType)l.push(new k4(a,b,c,d,n.nodeValue,e||0<m,g.Xb(k)?void 0:k));else{var p={};g.Da(p,k);IDa(a,b,c,d,e||0<m,n,p,l)}}},G4=function(a,b){D4.call(this);
this.J=b;this.C={};this.K={};this.L={};this.D="_"+m4++;this.F=a;this.H={};this.A=this.o=null;this.G=!0},H4=function(a,b){var c=a.getAttribute(b);
if(null!=c)return(0,window.parseFloat)(c)},I4=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},J4=function(a,b){var c=H4(a,b);
if(void 0!=c)return c},K4=function(a,b){var c=a.getAttribute(b);
if(null!=c)return F4.test(c),c},JDa=function(a,b){var c={},d=b.getAttribute("ws");
g.Da(c,d?a.L[d]:a.F);d=J4(b,"mh");null!=d&&(c.bv=d);d=J4(b,"ju");null!=d&&(c.textAlign=d);d=J4(b,"pd");null!=d&&(c.ci=d);d=J4(b,"sd");null!=d&&(c.wx=d);d=K4(b,"wfc");null!=d&&(c.windowColor=d);d=H4(b,"wfo");void 0!=d&&(c.windowOpacity=d/255);return c},KDa=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Da(c,a.K[d]);d=J4(b,"ap");null!=d&&(c.kh=d);d=H4(b,"cc");null!=d&&(c.Oo=d);d=H4(b,"ah");null!=d&&(c.lg=d);d=H4(b,"rc");null!=d&&(c.oj=d);d=H4(b,"av");null!=d&&(c.gi=d);return c},LDa=function(a,b,c,d){var e={};
g.Da(e,KDa(a,b));g.Da(e,JDa(a,b));d?g.ac(e,a.F)?(d=a.D,e=a.F):d="_"+m4++:d=b.getAttribute("id")||"_"+m4++;a=H4(b,"t")+c;b=H4(b,"d")||0x8000000000000;return new l4(a,b,0,d,e)},L4=function(a,b,c){this.G=c;
this.version=this.F=this.C=this.o=0;this.A=new window.DataView(a);this.B=[]},M4=function(a){var b=a.o;
a.o+=1;return a.A.getUint8(b)},N4=function(a){var b=a.o;
a.o+=4;return a.A.getUint32(b)},O4=function(a,b){D4.call(this);
this.A=a;this.track="CC3"==b.C?4:0;this.o=new r4;this.o.B=1<<this.track},NDa=function(a){if(g.v(a))return!1;
a=new L4(a,8,0);return MDa(a)},MDa=function(a){if(!(a.o<a.A.byteLength)||1380139777!=N4(a))return!1;
a.version=M4(a);if(1<a.version)return!1;M4(a);M4(a);M4(a);return!0},ODa=function(){this.A=[];
this.o=[]},P4=function(a,b){return b?a.o.concat(a.A):a.o},Q4=function(a,b){switch(b.B){case "asr":var c=a.A;
g.Ha(c,(0,g.B)(b.lv,b))||c.push(b);break;default:c=a.o,g.Ha(c,(0,g.B)(b.lv,b))||c.push(b)}},R4=function(){D4.call(this)},PDa=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.Cf=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var p=k.childNodes[n];if(3==p.nodeType){p=new k4(b,c,d,e.id,p.nodeValue,f||0<n,g.Xb(l)?void 0:l);m.push(p);var t=e;g.O(t,p);t.A.push(p)}else t={},g.Da(t,l),PDa(a,b,c,d,e,!0,p,t,m)}},S4=function(a){var b=0;
a=g.q(a.split(":"));for(var c=a.next();!c.done;c=a.next())b=60*b+(0,window.parseFloat)(c.value);return 1E3*b},QDa=function(a,b,c,d){d=Object.assign({bv:0},d);
return new l4(a,b,c,"_"+m4++,d)},T4=function(a,b){g.M.call(this);
this.F=a;this.MB=!!b;this.B=new ODa;this.H=[];this.o=null},SDa=function(a){var b={};
if(a=j4(a))b.lang=a,RDa.test(a)&&(b.ci=1);return b},U4=function(a,b){T4.call(this,a,b.Ho);
this.C=void 0;this.A=null;this.H=b.captionTranslationLanguages},V4=function(a,b,c,d,e,f,k){o4.call(this,a,b,c,d,e,f,k);
g.T(this.element,"ytp-caption-window-rollup");this.type=2;this.U=this.Z=this.la=this.ha=0;this.K=this.M=this.O=window.NaN;this.Aa=null;this.aa=new g.Eu(this.DQ,433,this);g.O(this,this.aa)},W4=function(a){if(!a.ha){var b=g.Rd("SPAN");
g.yh(b,p4(a,a.B.Jb));a.C.appendChild(b);b.appendChild(g.Sd("M"));var c=b.offsetHeight,d=g.Rd("BR");b.appendChild(d);b.appendChild(g.Sd("M"));a.ha=b.offsetHeight-c;a.C.removeChild(b)}return a.ha},X4=function(a){if(!a.la){var b=g.Rd("SPAN");
g.yh(b,p4(a,a.B.Jb));sDa(a,b);a.C.appendChild(b);b.appendChild(g.Sd("\u9b31"));var c=b.offsetWidth,d=g.Rd("BR");b.appendChild(d);b.appendChild(g.Sd("\u9b31"));a.la=b.offsetWidth-c;a.C.removeChild(b)}return a.la},TDa=function(a){if((0,window.isNaN)(a.O)){var b=a.B.Oo;
if(b){var c=g.Rd("SPAN");g.fe(c,"\u2013".repeat(b));g.yh(c,p4(a,a.B.Jb));a.C.appendChild(c);a.O=c.offsetWidth;a.C.removeChild(c)}else a.O=0}return a.O},UDa=function(a){if((0,window.isNaN)(a.M)){var b=a.B.Oo;
if(b){var c=g.Rd("SPAN");g.fe(c,"\u53e3".repeat(b));g.yh(c,p4(a,a.B.Jb));a.C.appendChild(c);a.M=c.offsetHeight;a.C.removeChild(c)}else a.M=0}return a.M},Y4=function(){this.vb=[]},Z4=function(a,b,c,d,e,f){g.M.call(this);
this.L=a;this.C=b;this.F=new Y4;this.o=null;this.J=d;this.M=f;this.A=this.B=null;this.H=c;this.G=e||!1;this.K=new g.Eu(this.dC,1E3,this);g.O(this,this.K);this.D=new g.dG(this);g.O(this,this.D);g.X(b).experiments.o("html5_disable_captions_seek_complete")?this.D.R(b,"seekto",this.iD):this.D.R(b,"seekcomplete",this.FQ);this.iD(b.getCurrentTime());this.dC()},$4=function(a,b){b-=g.$T(a.C);
var c=a.o;a.o=g.Fa(a.H.Mg(b).o);c!=a.o&&a.M&&a.M()},VDa=function(a,b){var c=g.KL(b,a.L,{}).Xa(),d={format:"RAW",
withCredentials:!0};a.G&&(d.responseType="arraybuffer");a.A=g.lF(c,d,3,100).then((0,g.B)(a.pV,a));a.B=b;c=a.F;d=a.B.o[0].A;var e=g.bb(c.vb,d);0<=e||0>e&&1==(-e-1)%2||(e=-e-1,0<e&&1==d-c.vb[e-1]&&e<c.vb.length&&1==c.vb[e]-d?(g.Ra(c.vb,e),g.Ra(c.vb,e-1)):0<e&&1==d-c.vb[e-1]?c.vb[e-1]=d:e<c.vb.length&&1==c.vb[e]-d?c.vb[e]=d:(g.Ya(c.vb,e,0,d),g.Ya(c.vb,e+1,0,d)))},a5=function(a,b){T4.call(this,g.X(b));
this.A=a;this.D=b;this.C=null;this.G=!1;this.J=g.CN(g.X(this.D))&&!this.A.A;this.K=g.X(this.D).experiments.o("web_player_enforce_format3_manifestless_captions_killswitch")},b5=function(a,b){var c=[],d;
for(d in a.A.o){var e=a.A.o[d];if(WDa(e,b||null)){var f="en",k="English",l=".en",m="";if(e=e.info.captionTrack)f=e.languageCode,k=e.displayName,l=e.vssId,m=e.kind;c.push(new g.tI({id:d,format:3,languageCode:f,languageName:k,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},WDa=function(a,b){return g.KI(a.info.mimeType)?b?g.DI(a.info)==b:!0:!1},XDa=function(a,b){return null!=b&&b in a.A.o?a.A.o[b]:null},c5=function(a,b,c){var d=[],e;
for(e in a.A.o){var f=a.A.o[e];if(WDa(f,c||null)){var k=f.info.captionTrack;k&&k.languageCode==b&&d.push(f)}}return d.length?d[0]:null},d5=function(a,b,c,d,e,f,k){o4.call(this,a,b,c,d,e,f,k);
this.type=1},e5=function(a,b,c,d,e,f,k){o4.call(this,a,b,c,d,e,f,k);
g.T(this.element,"ytp-caption-window-rollup");this.type=2;this.K=[];this.O=this.M=this.aa=0;this.U=window.NaN;this.la=0;this.ha=null;this.Z=new g.Eu(this.EQ,433,this);g.O(this,this.Z)},YDa=function(a,b){return(a.G?b.offsetHeight:b.offsetWidth)+1},ZDa=function(a){if((0,window.isNaN)(a.U)){var b=a.B.Oo;
if(b){var c=g.Rd("SPAN");g.fe(c,"\u2013".repeat(b));g.yh(c,p4(a,a.B.Jb));a.C.appendChild(c);a.U=c.offsetWidth;a.C.removeChild(c)}else a.U=0}return a.U},$Da=function(a,b){if(!b)return"";
a.G&&1!=a.D.params.wx&&(b*=-1);return"translate"+(a.G?"X":"Y")+"("+b+"px)"},aEa=function(a){a.K=Array.prototype.slice.call(g.Dd("ytp-rollup-caption-line"));
for(var b=a.D.params.oj,c=0,d=0,e=a.K.length-1;c<b&&-1<e;){var f=a.K[e];d+=a.G?f.offsetWidth:f.offsetHeight;c++;e--}a.K.length<b&&(d*=b/a.K.length);a.M=d;a.O=Math.max(ZDa(a),a.la,YDa(a,a.C))},bEa=function(a,b){aEa(a);
var c=a.K.reduce(function(b,c){return(a.G?c.offsetWidth:c.offsetHeight)+b},0);
c=a.M-c;if(c!=a.aa){var d=0<c&&0==a.aa;b||(0,window.isNaN)(c)||d||(g.T(a.element,"ytp-rollup-mode"),g.Fu(a.Z));g.yh(a.C,"transform",$Da(a,c));a.aa=c}aEa(a)},f5=function(a,b,c,d,e){T4.call(this,e||null,d);
c=c||g.FE(a).hl||"";c=c.split("_").join("-");this.D=g.HE(a,{hl:c});this.C=b;this.G={};this.A=null},i5=function(a){g.iU.call(this,a);
this.B=g.X(a);this.D=a.getVideoData();this.wa=g.FT(a);this.L=a;var b=null,c=g.TD("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.CD(c));this.aa=b;this.C={Jb:{}};this.F={Jb:{}};this.K=[];this.O={};this.ba={};this.M=!1;b=this.D;c=this.L;this.ha=b.mk()&&null!=b.ua||null!=b.ua&&g.CN(g.X(c))&&!b.ua.A&&null!=b.ua.o.rawcc;this.za=this.D.In||this.B.In||this.ha;this.na="3"==this.B.C;b=g.ZT(a);c=!(!b||!b.Jn());this.ra=!(!b||!b.tj());this.G=this.na&&c&&!this.ha;this.Z=!this.G&&this.na&&this.ra&&
this.ha;c=b=this.o=this.A=this.H=this.J=this.U=this.ka=null;this.G||(b=new g.Bu(this.WG,void 0,this),g.O(this,b),c=new g.Eu(this.fX,2E3,this),g.O(this,c));this.ca=b;this.ga=c;this.Y=new g.dG(this);g.O(this,this.Y);this.G||this.Y.R(a,"resize",this.Ex);this.Y.R(a,"onPlaybackAudioChange",this.oS);this.Y.R(a,g.VP("captions"),this.zO,this);this.Y.R(a,"crx_captions",this.AO,this);g5(this,h5(this,"display-settings")||{})},cEa=function(a){if(1==a.B.oh||1==a.D.oh||"alwayson"==g.RO(a.D,"yt:cc"))return!0;
if(2==a.B.oh){var b=h5(a,"module-enabled");if(null!=b)return!!b}if(a.D.captionTracks.length)var c=a.player.getAudioTrack().Ns;return"ON"==c||"on"==g.RO(a.D,"yt:cc")},j5=function(a,b){if(a.o&&(void 0===b||!b)||!a.D.captionTracks.length)return!1;
var c=a.player.getAudioTrack();return!!c.kp||"FORCED_ON"==c.Ns},l5=function(a,b){if(a.A){var c=P4(a.A.B,b||a.za);
if(a.H&&a.H.o)return a.H.o;for(var d=[a.D.nh,a.B.nh,g.RO(a.D,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(j4(c[f])==d[e])return c[f];return a.H&&a.H.lt?a.H.lt:(d=c.find(function(a){return a.isDefault}))?d:c[0]||k5(a)}return null},k5=function(a){return a.H&&a.H.kp},m5=function(a){var b=k5(a);
return!!b&&a.o==b},dEa=function(a,b){for(var c=g.ZT(a.L).oa().textTracks,d=a.o.toString(),e=0;e<c.length;e++){var f=c[e];
f.id==d&&(b?"showing"!=f.mode&&(f.mode="showing"):"showing"==f.mode&&(f.mode="disabled"))}},o5=function(a,b,c,d){a.loaded&&a.unload();
null!=c&&(a.M=c,a.M&&n5(a,"module-enabled",!!b));a.o=b;j5(a)&&(a.o=k5(a));a.load(d)},eEa=function(a,b){var c=g.c_(a.wa,!0).height;
if(!c)return null;var d=a.wa.Va();switch(null!=b.params.bv?b.params.bv:1<b.A.length?1:0){case 1:return new d5(b,a.C,a.F,c,d.width,d.height,a.B.experiments);case 2:return a.B.experiments.o("web_player_new_rollup_captions")?new e5(b,a.C,a.F,c,d.width,d.height,a.B.experiments):new V4(b,a.C,a.F,c,d.width,d.height,a.B.experiments);default:return new o4(b,a.C,a.F,c,d.width,d.height,a.B.experiments)}},g5=function(a,b,c){var d=p5.Jb;
a.C={};g.Da(a.C,p5);a.C.Jb={};g.Da(a.C.Jb,d);a.F={Jb:{}};var e=b.backgroundOverride?a.F:a.C,f=b.background||d.background;F4.test(f);e.Jb.background=f;e=b.colorOverride?a.F:a.C;f=b.color||d.color;F4.test(f);e.Jb.color=f;e=b.windowColorOverride?a.F:a.C;f=b.windowColor||p5.windowColor;F4.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.F:a.C;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.Jb.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.F:a.C;f=b.fontSizeIncrement;null==f&&(f=d.fontSizeIncrement);
e.Jb.fontSizeIncrement=f;f=b.fontStyleOverride?a.F:a.C;e=b.fontStyle;null==e&&(e=d.bold&&d.Cf?3:d.bold?1:d.Cf?2:0);f=f.Jb;switch(e){case 1:f.bold=!0;delete f.Cf;break;case 2:delete f.bold;f.Cf=!0;break;case 3:f.bold=!0;f.Cf=!0;break;default:delete f.bold,delete f.Cf}e=b.textOpacityOverride?a.F:a.C;f=b.textOpacity;null==f&&(f=d.textOpacity);e.Jb.textOpacity=f;e=b.windowOpacityOverride?a.F:a.C;f=b.windowOpacity;null==f&&(f=p5.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?a.F:a.C;f=b.charEdgeStyle;
null==f&&(f=d.charEdgeStyle);e.Jb.charEdgeStyle=f;e=b.fontFamilyOverride?a.F:a.C;f=b.fontFamily;null==f&&(f=d.fontFamily);e.Jb.fontFamily=f;a.loaded&&a.Ex();c&&n5(a,"display-settings",b)},gEa=function(a,b){if(b&&!a.J){var c=n4({ci:0,
lang:"fr"});a.J=[c,new k4(c.start,c.end-c.start,0,c.id,"Aper\u00e7u des sous-titres")];g.RT(a.player,a.J)}else!b&&a.J&&(fEa(a,a.J),a.J=null)},fEa=function(a,b){g.UT(a.player,b);
(0,g.D)(b,function(a){g.Sa(this.K,a)},a);
a.ca.Wj()},hEa=function(a,b){return a&&g.v(a)&&F4.test(a)?a:b},iEa=function(a,b){return g.sa(a)&&!(0,window.isNaN)(a)?Math.max(0,Math.min(1,(0,window.parseFloat)(a))):b},jEa=function(a,b){return g.sa(a)&&!(0,window.isNaN)(a)?g.md(a,-2,4):b},h5=function(a,b){if(!a.aa)return null;
try{var c=a.aa.get(b)}catch(d){a.aa.remove(b)}return c},n5=function(a,b,c){if(a.aa)try{a.aa.set(b,c)}catch(d){}};
g.bQ.prototype.Cl=g.ca(12,function(){for(var a=g.Cd(window.document,"track",void 0,this.o),b=0;b<a.length;b++)g.Xd(a[b])});
g.aS.prototype.Cl=g.ca(11,function(){this.A.Cl()});
g.bQ.prototype.Jn=g.ca(10,function(){return!!this.o.textTracks});
g.aS.prototype.Jn=g.ca(9,function(){return this.A.Jn()});
g.bQ.prototype.ul=g.ca(8,function(a){for(var b=0;b<a.length;b++)this.o.appendChild(a[b])});
g.aS.prototype.ul=g.ca(7,function(a){this.A.ul(a)});
g.gP.prototype.tj=g.ca(6,function(){});
g.bQ.prototype.tj=g.ca(5,function(){return!(!this.o.textTracks||!this.o.textTracks.addEventListener)});
g.aS.prototype.tj=g.ca(4,function(){return this.A.tj()});
g.TJ.prototype.xp=g.ca(2,function(a){return(a=this.sh(a))?a.A:0});
g.bM.prototype.xp=g.ca(1,function(){return 0});
g.tI.prototype.lv=g.ca(0,function(a){return a?this.toString()==a.toString():!1});
var RDa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,F4=/^#(?:[0-9a-f]{3}){1,2}$/i;var rDa=["left","right","center","justify"];var p5={windowColor:"#080808",windowOpacity:0,textAlign:2,kh:7,lg:50,gi:100,Jb:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.r(k4,g.TP);k4.prototype.toString=function(){return g.TP.prototype.toString.call(this)};g.r(l4,g.TP);l4.prototype.toString=function(){return g.TP.prototype.toString.call(this)};
var m4=0;g.r(o4,g.V);g.h=o4.prototype;g.h.CQ=function(a,b){var c=g.Oh(this.element,this.element.parentElement);this.ra=a-c.x;this.wa=b-c.y;g.T(this.element,"ytp-dragging")};
g.h.BQ=function(a,b){var c=g.Rh(this.element),d=a-this.ra-.02*this.bb,e=b-this.wa-.02*this.Ua,f=(d+c.width/2)/this.ka*3;f=Math.floor(g.md(f,0,2));var k=(e+c.height/2)/this.za*3;k=Math.floor(g.md(k,0,2));var l=f+3*k;d=(d+f/2*c.width)/this.ka;d=100*g.md(d,0,1);c=(e+k/2*c.height)/this.za;c=100*g.md(c,0,1);this.D.params.kh=l;this.D.params.gi=c;this.D.params.lg=d;this.B.kh=l;this.B.gi=c;this.B.lg=d;this.Vw()};
g.h.AQ=function(){g.Qq(this.element,"ytp-dragging")};
g.h.Vw=function(){this.lf(this.F)};
g.h.Yb=function(){return this.type};
g.h.lf=function(a){var b=Math.min(this.Jt(),this.ka),c=this.It(),d="";3==this.D.params.ci&&(d="rotate(180deg)");g.yh(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.Ds(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.B.lg+2;d=this.B.kh;switch(d){case 0:case 3:case 6:a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.C.offsetWidth;
b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.B.gi+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.yh(this.element,a)};
g.h.Ds=function(a){var b;for(b=0;b<a.length&&a[b]==this.F[b];b++);if(this.ca||this.F.length>b)b=0,this.ca=!1,this.F=[],this.J=[],this.L=[],this.H=null,g.Vd(this.C);for(;b<a.length;b++)tDa(this,a[b])};
g.h.Jt=function(){return 0};
g.h.It=function(){return 0};
g.h.Fl=function(a){a.appendChild(g.Sd("\u00a0"));this.H=g.Rd("SPAN");a.appendChild(this.H);g.T(this.H,"caption-visual-line");a.appendChild(g.Sd("\u00a0"))};
g.h.toString=function(){return g.V.prototype.toString.call(this)};uDa.prototype.D=function(){};r4.prototype.clear=function(){this.C=this.A=this.mode=0;this.o=[];this.reset()};
r4.prototype.reset=function(){this.mode=0;this.D.reset(0);this.F.reset(1)};
var vDa=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];s4.prototype.set=function(a){this.o=a};
s4.prototype.get=function(){return this.o};
t4.prototype.clear=function(){this.o=0};
t4.prototype.update=function(){this.o=2==this.o?1:0};
t4.prototype.matches=function(a,b){return 0!=this.o&&a==this.B&&b==this.A};
u4.prototype.To=function(a){this.Ne=a.Ne;this.timestamp=a.timestamp};
u4.prototype.reset=function(){this.timestamp=this.Ne=0};
v4.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.B[b][c];a=0==d.Ne?a+"_":a+String.fromCharCode(d.Ne)}a+="\n"}return a};
v4.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.B[b][c].reset();this.C=a;this.o=0;this.A=this.row=1};
var ADa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],BDa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],CDa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],DDa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];B4.prototype.reset=function(a,b){this.D=b;this.style.set(2);this.A=this.F;this.B=this.G;this.o=this.A;var c=(a<<2)+(b<<1);this.F.reset(c);this.G.reset(c);this.H.reset((a<<2)+(b<<1)+1)};
q4.prototype.reset=function(a){this.D=a;this.o.clear();this.C=this.B;this.B.reset(a,0);this.F.reset(a,1)};g.r(D4,g.M);D4.prototype.reset=function(){};g.r(E4,D4);
E4.prototype.B=function(a){var b=a.firstChild;a=[];this.o||(this.o=n4(this.A),a.push(this.o));b=Array.from(b.childNodes);b=g.q(b);for(var c=b.next();!c.done;c=b.next()){c=c.value;var d=this.o.id,e=c.getAttribute("t");e=e?(0,window.parseInt)(e,10):1E3*(0,window.parseFloat)(c.getAttribute("start")||0);var f=c.getAttribute("d");f=f?(0,window.parseFloat)(f):1E3*(0,window.parseFloat)(c.getAttribute("dur")||0);d=c.getAttribute("w")||d;var k=!!c.getAttribute("append"),l=k?6:5;c=g.zs("<html>"+(c.firstChild&&
c.firstChild.nodeValue||"")+"</html>");IDa(e,f,l,d,k,c.firstChild,{},a)}return a};g.r(G4,D4);G4.prototype.reset=function(){this.H={};this.A=this.o=null;this.G=!0};
G4.prototype.B=function(a,b){var c=a.firstChild;c.getAttribute("format");b=b||0;Number.isFinite(b);c=Array.from(c.childNodes);c=g.q(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "head":var e=d;break;case "body":var f=d}if(e)for(e=Array.from(e.childNodes),e=g.q(e),c=e.next();!c.done;c=e.next())if(c=c.value,1==c.nodeType)switch(c.tagName){case "pen":d=c.getAttribute("id");var k=this.C,l={},m=c.getAttribute("p");m&&g.Da(l,this.C[m]);m=I4(c,"b");null!=m&&(l.bold=
m);m=I4(c,"i");null!=m&&(l.Cf=m);m=I4(c,"u");null!=m&&(l.underline=m);m=J4(c,"et");null!=m&&(l.charEdgeStyle=m);m=J4(c,"of");null!=m&&(l.offset=m);m=K4(c,"bc");null!=m&&(l.background=m);m=K4(c,"ec");null!=m&&(l.Rz=m);m=K4(c,"fc");null!=m&&(l.color=m);m=J4(c,"fs");void 0!=m&&0!=m&&(l.fontFamily=m);m=H4(c,"sz");void 0!=m&&(l.fontSizeIncrement=m/100-1);m=H4(c,"bo");void 0!=m&&(l.backgroundOpacity=m/255);m=H4(c,"fo");void 0!=m&&(l.textOpacity=m/255);c=J4(c,"rb");void 0!=c&&(l.lX=c);k[d]=l;break;case "ws":d=
c.getAttribute("id");this.L[d]=JDa(this,c);break;case "wp":d=c.getAttribute("id"),this.K[d]=KDa(this,c)}if(f){e=b;c=[];f=Array.from(f.childNodes);f=g.q(f);for(d=f.next();!d.done;d=f.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "w":this.o=LDa(this,d,e,!1);g.O(this,this.o);(d=this.H[this.o.id])&&d.end>this.o.start&&(d.end=this.o.start);this.H[this.o.id]=this.o;c.push(this.o);break;case "p":var n=e;k=[];l=d.getAttribute("w")||this.D;m=!!I4(d,"a");n=(H4(d,"t")||0)+n;var p=H4(d,"d")||5E3;m||
(!this.G&&this.A&&this.A.windowId==l&&this.A.end>n&&(this.A.end=n),this.A&&"\n"==this.A.text&&(this.A.text=""));var t=m?6:5,w=this.C[d.getAttribute("p")],z=d.childNodes;z.length&&(this.G=null!=d.getAttribute("d"));for(var E=0;E<z.length;E++){var I=z[E];0<E&&(m=!0);var N=void 0;1==I.nodeType&&(N=I);if(N&&"s"==N.tagName)if(I=this.C[N.getAttribute("p")],!I||1!=I.lX||this.J&&!this.J.experiments.o("web_player_ruby_text_captions")){var K=N;I=n;var Qa=p,ob=l,ic=m,de=t;N=K.textContent?K.textContent:"";var Ia=
this.C[K.getAttribute("p")];K=H4(K,"t")||0;I=new k4(I+K,Qa-K,de,ob,N,ic,Ia)}else{I=n;Qa=p;ob=l;ic=m;de=t;Ia=N;var Lc=z[E+1],Ad=z[E+2];K=z[E+3];Ia.getAttribute("p");H4(Ia,"t");H4(Lc,"t");H4(Ad,"t");H4(K,"t");N=g.Rd("RUBY");Ia=Ia.textContent;var Qd=g.Rd("SPAN");Qd.innerText=Ia;N.appendChild(Qd);Lc.getAttribute("p");Qd=g.Rd("RP");Ia=Lc.textContent;Qd.innerText=Ia;N.appendChild(Qd);Ad.getAttribute("p");Ia=Ad.textContent;Lc=g.Rd("RT");Lc.innerText=Ia;N.appendChild(Lc);K.getAttribute("p");Ia=K.textContent;
K=g.Rd("RP");K.innerText=Ia;N.appendChild(K);I=new k4(I,Qa,de,ob,N,ic,null);E+=3}else I=new k4(n,p,t,l,I.textContent||"",m,w);k.push(I);this.A=I}if(0<k.length)for(k[0].windowId==this.D&&(this.o=LDa(this,d,e,!0),g.O(this,this.o),c.push(this.o)),d=g.q(k),k=d.next();!k.done;k=d.next())k=k.value,k.windowId=this.o.id,l=this.o,g.O(l,k),l.A.push(k),c.push(k)}e=c}else e=[];return e};g.r(L4,uDa);L4.prototype.D=function(a,b,c,d,e){if(c<d){var f="_"+m4++;c=c/1E3-this.G;d=d/1E3-this.G;a=new l4(c,d-c,5,f,{textAlign:0,kh:0,lg:2.5*b,gi:5.33*a});e=new k4(c,d-c,5,f,e);this.B.push(a);this.B.push(e)}};
g.r(O4,D4);O4.prototype.B=function(a){a=new L4(a,a.byteLength,this.A);if(MDa(a)){for(;a.o<a.A.byteLength;)for(0==a.version?a.C=N4(a)*(1E3/45):1==a.version&&(a.C=4294967296*N4(a)+N4(a)),a.F=M4(a);0<a.F;a.F--){var b=M4(a),c=M4(a),d=M4(a);b&4&&(b&3)==this.track&&(0==this.track||1==this.track)&&(b=this.o,b.o.push({time:a.C,type:this.track,Mz:c,Nz:d,order:b.o.length}))}zDa(this.o,a);return a.B}return[]};
O4.prototype.reset=function(){this.o.clear()};g.r(R4,D4);
R4.prototype.B=function(a,b){for(var c=[],d=a.split(kEa),e=1;e<d.length;e++){var f=d[e],k=b;if(""!=f&&!lEa.test(f)){var l=q5.exec(f);if(l&&4<=l.length){var m=S4(l[1]),n=S4(l[2])-m;m+=k;var p,t=p=void 0,w=void 0,z=void 0,E=l[3];l={textAlign:2};E=g.q(E?E.split(" "):[]);for(var I=E.next();!I.done;I=E.next())if(I=I.value.split(":"),2==I.length){var N=I[1];switch(I[0]){case "line":I=N.split(",");I[0].endsWith("%")&&(z=I[0],l.gi=Number.parseInt(z,10),2==I.length&&(w=I[1].trim()));break;case "position":I=N.split(",");
t=I[0];l.lg=Number.parseInt(t,10);2==I.length&&(p=I[1].trim());break;case "align":switch(N){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}z||(l.gi=100,w||(w="end"));if(!t)switch(l.textAlign){case 0:l.lg=0;break;case 1:l.lg=100;break;default:l.lg=50}t=0;switch(w){case "center":t+=3;break;case "end":t+=6;break;default:t+=0}switch(p){case "line-left":t+=0;break;case "center":t+=1;break;case "line-right":t+=2;break;default:switch(l.textAlign){case 0:t+=
0;break;case 2:t+=1;break;case 1:t+=2}}l.kh=0>t||8<t?7:t;p=l;f=f.substring(q5.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");t=p;p=f;f={};if(0>p.indexOf("<")&&0>p.indexOf("&"))k=QDa(m,n,5,t),n=new k4(m,n,5,k.id,p,!1,g.Xb(f)?void 0:f),c.push(k),c.push(n),g.O(k,n),k.A.push(n);else for(w=p.split(mEa),1==w.length?(p=5,t=QDa(m,n,p,t)):(z=p=6,t=Object.assign({Oo:32},t),t=new l4(m,n,z,"_"+m4++,t)),c.push(t),z=m,l=0;l<w.length;l++)E=w[l],0==l%2?(I=g.zs("<html>"+E+"</html>"),I.getElementsByTagName("parsererror").length?
(N=I.createElement("span"),N.appendChild(I.createTextNode(E))):N=I.firstChild,PDa(this,z,n-(z-m),p,t,0<l,N,f,c)):z=S4(E)+k}q5.lastIndex=0}}return c};
var lEa=/^NOTE/,kEa=/(?:\r\n|\r|\n){2,}/,q5=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),mEa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.r(T4,g.M);T4.prototype.be=function(){this.o&&this.o.dispose();this.o=null};
T4.prototype.X=function(){g.M.prototype.X.call(this);this.be()};
T4.prototype.qF=function(){return!1};g.r(U4,T4);g.h=U4.prototype;g.h.Vu=function(a,b){var c=this.fm(a),d=(0,g.B)(function(c){this.A=null;b(c.responseText,a)},this);
this.be();this.A=g.PE(c,{format:"RAW",onSuccess:d,withCredentials:!0})};
g.h.Wu=function(a,b,c,d){this.C=c;if(d)for(b=g.q(d.captionTracks),c=b.next();!c.done;c=b.next())Q4(this.B,c.value);a()};
g.h.fm=function(a){var b=a.Xa(),c={};if(this.C||a.G)c.fmt=this.C||"srv"+a.G;a.o&&(c.tlang=a.o.languageCode);return g.HE(b,c)};
g.h.be=function(){T4.prototype.be.call(this);this.A&&this.A.abort()};
g.h.X=function(){this.be();T4.prototype.X.call(this)};g.r(V4,o4);g.h=V4.prototype;g.h.Vw=function(){g.Gu(this.aa)};
g.h.DQ=function(){g.Qq(this.element,"ytp-rollup-mode");this.lf(this.Aa,!0)};
g.h.Jt=function(){return this.G?this.D.params.oj*X4(this):this.Z};
g.h.It=function(){return this.G?this.U:this.D.params.oj*W4(this)};
g.h.Fl=function(a){o4.prototype.Fl.call(this,a);g.yh(this.H,"display","inline-block")};
g.h.lf=function(a,b){this.Aa=a;if(!this.G&&!W4(this)||this.G&&!X4(this))o4.prototype.lf.call(this,a);else{for(var c=0,d=0;d<this.F.length&&c<a.length;d++)this.F[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.F.concat(a.slice(c)));c=this.Z;d=this.U;this.U=this.Z=0;o4.prototype.lf.call(this,a);this.G?(c=this.C.offsetHeight+1,this.U=Math.max(UDa(this),d,c),c=this.D.params.oj*X4(this)-this.C.offsetWidth,1!=this.D.params.wx&&(c*=-1),c!=this.K&&(b||(0,window.isNaN)(this.K)||(g.T(this.element,"ytp-rollup-mode"),
g.Fu(this.aa)),g.yh(this.C,"transform",c?"translateX("+c+"px)":""),this.K=c)):(d=this.C.offsetWidth+1,this.Z=Math.max(TDa(this),c,d),c=this.D.params.oj*W4(this)-this.C.offsetHeight,c!=this.K&&(b||(0,window.isNaN)(this.K)||(g.T(this.element,"ytp-rollup-mode"),g.Fu(this.aa)),g.yh(this.C,"transform",c?"translateY("+c+"px)":""),this.K=c));o4.prototype.lf.call(this,a)}};Y4.prototype.contains=function(a){a=g.bb(this.vb,a);return 0<=a||0>a&&1==(-a-1)%2};
Y4.prototype.length=function(){return this.vb.length/2};g.r(Z4,g.M);g.h=Z4.prototype;g.h.X=function(){g.M.prototype.X.call(this);this.A&&this.A.cancel()};
g.h.iD=function(a){var b=this;if(this.H.lk())var c=this.D.R(this.C,"progresssync",function(){b.H.index.Pb()&&(b.reset(),b.o=null,$4(b,b.C.getCurrentTime()),b.D.Ka(c))});
else $4(this,a)};
g.h.FQ=function(){$4(this,this.C.getCurrentTime())};
g.h.reset=function(){this.F=new Y4;this.A&&(this.A.cancel(),this.A=null)};
g.h.dC=function(){var a;if(a=null!==this.o)a=this.o,a=a.o.Tg(a);!a||this.A||this.o&&30<this.o.startTime-this.C.getCurrentTime()||(a=this.o,a=a.o.uk(a),a.o[0].duration&&(this.F.contains(a.o[0].A)||VDa(this,a),this.o=g.Fa(a.o)));this.K.start()};
g.h.pV=function(a){var b=!(this.G?a.response:a.responseText)||400<=a.status,c=g.gM(a);c?(a=g.KL(this.B,this.L,{}),b=this.B,g.FL(b.A,a,c),b.requestId=a.get("req_id"),VDa(this,this.B)):(b||null===this.J||(this.G?this.J(a.response,1E3*(this.B.o[0].startTime+g.$T(this.C))):this.J(a.responseText,1E3*(this.B.o[0].startTime+g.$T(this.C)))),this.A=this.B=null)};g.r(a5,T4);g.h=a5.prototype;g.h.Vu=function(a,b){this.be();var c=XDa(this,a.getId());if(!c){var d=a.A;this.A.A?(c=c5(this,d,"386"),!c&&this.K&&(c=c5(this,d,"387"))):c=c5(this,d)}if(c){var e=1E3*(c.index.xp(c.index.yf())-c.index.ae(c.index.yf()));this.C=new Z4(new g.mL,this.D,c,function(c,d){b(c,a,d,e)},this.J||g.HI(c.info),(0,g.B)(function(){this.C&&this.C.reset();
this.o&&this.o.reset();this.G=!0},this))}};
g.h.qF=function(){var a=this.G;this.G=!1;return a};
g.h.Wu=function(a){if(this.J)var b=[new g.tI({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.tI({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})];else this.A.A?(b=b5(this,"386"),!b.length&&this.K&&(b=b5(this,"387"))):b=b5(this);b=g.q(b);for(var c=b.next();!c.done;c=b.next())Q4(this.B,c.value);a()};
g.h.be=function(){T4.prototype.be.call(this);this.C&&(this.C.dispose(),this.C=null)};
g.h.fm=function(){return""};
g.h.X=function(){this.be();T4.prototype.X.call(this)};g.r(d5,o4);d5.prototype.Ds=function(a){var b=this.D.A;o4.prototype.Ds.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.A==e)var d=f;else{d={};g.Da(d,c.A);g.Da(d,nEa);var e=c.A;var f=d}tDa(this,c,d)}};
var nEa={Fp:!0};g.r(e5,o4);g.h=e5.prototype;g.h.Vw=function(){g.Gu(this.Z)};
g.h.EQ=function(){g.Qq(this.element,"ytp-rollup-mode");this.lf(this.ha,!0)};
g.h.It=function(){return this.G?this.O:this.M};
g.h.Jt=function(){return this.G?this.M:this.O};
g.h.Fl=function(a){o4.prototype.Fl.call(this,a);g.yh(this.H,"display","inline-block");g.T(this.H,"ytp-rollup-caption-line")};
g.h.lf=function(a,b){this.ha=a;if(this.D.params.oj){for(var c=0,d=0;d<this.F.length&&c<a.length;d++)this.F[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.F.concat(a.slice(c)));this.la=this.O;this.M=this.O=0;o4.prototype.lf.call(this,a);bEa(this,b);o4.prototype.lf.call(this,a)}else o4.prototype.lf.call(this,a)};g.r(f5,T4);g.h=f5.prototype;g.h.Vu=function(a,b){var c=this.fm(a),d=(0,g.B)(function(c){this.A=null;b(c.responseText,a)},this);
this.be();this.A=g.PE(c,{format:"RAW",onSuccess:d,withCredentials:!0})};
g.h.Wu=function(a,b,c){var d=this.D;b={type:"list",tlangs:1,v:this.C,fmts:Number(b||!1),vssids:1};this.MB&&(b.asrs=1);d=g.HE(d,b);b=(0,g.B)(function(b){this.A=null;if((b=b.responseXML)&&b.firstChild){for(var d=c||null,e=g.q(b.getElementsByTagName("track")),l=e.next();!l.done;l=e.next()){var m=l.value;l=m.getAttribute("lang_code");var n=m.getAttribute("lang_translated"),p=m.getAttribute("name"),t=m.getAttribute("kind"),w=m.getAttribute("id"),z="true"==m.getAttribute("lang_default"),E="true"==m.getAttribute("cantran");
m=m.getAttribute("vss_id");Q4(this.B,new g.tI({format:d||3,languageCode:l,languageName:n,name:p,kind:t,id:w,is_servable:!0,is_translateable:E,vss_id:m,is_default:z}))}b=b.getElementsByTagName("target");d=b.length;for(e=0;e<d;e++)l=b[e].getAttribute("lang_code"),n=b[e].getAttribute("lang_translated"),p=b[e].getAttribute("lang_original"),t=b[e].getAttribute("id"),w="true"==b[e].getAttribute("lang_default"),l={languageCode:l,languageName:n,languageOriginal:p,id:t,is_default:w},this.G[l.languageCode]=
l.languageName,this.H.push(new g.sI(l))}a()},this);
this.be();this.A=g.PE(d,{format:"RAW",onSuccess:b,withCredentials:!0})};
g.h.fm=function(a){var b=this.D,c={v:this.C,type:"track",lang:a.A,name:a.D,kind:a.B,fmt:a.G};a.o&&(c.tlang=j4(a));return b=g.HE(b,c)};
g.h.be=function(){T4.prototype.be.call(this);this.A&&this.A.abort()};
g.h.X=function(){this.be();T4.prototype.X.call(this)};g.r(i5,g.iU);g.h=i5.prototype;g.h.X=function(){if(this.G||this.Z){var a=g.ZT(this.L);a&&a.Cl()}else gEa(this,!1);g.iU.prototype.X.call(this)};
g.h.FC=function(){return this.na?this.G||this.Z:j5(this)?!0:cEa(this)};
g.h.load=function(a){g.iU.prototype.load.call(this);this.H=this.player.getAudioTrack();if(this.A||a)this.o&&(this.G?dEa(this,!0):a?this.WE(a,this.o):3!=this.player.Sa()&&this.A.Vu(this.o,(0,g.B)(this.WE,this))),this.o&&!m5(this)?this.player.ya("captionschanged",i4(this.o)):this.player.ya("onCaptionsTrackListChanged");else{var b;this.ha?b=new a5(this.D.ua,this.player):this.D.captionTracks.length?b=new U4(this.B,this.D):b=new f5(this.D.Io,this.D.videoId,this.D.nh||this.B.nh||g.RO(this.D,"yt:cc_default_lang")||
this.B.za,this.D.Ho,this.B);this.A=b;g.O(this,this.A);b.Wu((0,g.B)(this.YV,this),!0,this.G?"vtt":void 0,this.player.getAudioTrack())}};
g.h.unload=function(){this.G&&this.o?dEa(this,!1):(this.ga&&g.Hu(this.ga),g.VT(this.player,"captions"),this.K=[],this.A&&this.A.be(),this.J&&g.RT(this.player,this.J),this.Ex());g.iU.prototype.unload.call(this);var a=g.Y(this.player.app);a&&a.C&&g.dP(a.C.B);this.player.ya("captionschanged",{})};
g.h.YV=function(){var a;this.M||cEa(this)?a=l5(this,this.M):j5(this)&&(a=k5(this));if(this.G||this.Z){for(var b=P4(this.A.B,!0),c=[],d=0;d<b.length;d++){var e=b[d],f={kind:"subtitles",label:g.uI(e),srclang:j4(e),id:e.toString()};this.Z||(f.src=this.A.fm(e));e==a&&(f["default"]=1);c.push(g.Od("TRACK",f))}g.ZT(this.L).ul(c);a=g.ZT(this.L).oa();this.ra&&this.Y.R(a.textTracks,"change",this.ZV)}else!this.o&&a&&o5(this,a),this.player.ya("onCaptionsTrackListChanged"),this.player.ya("onApiChange")};
g.h.ZV=function(){for(var a=g.ZT(this.L).oa().textTracks,b=null,c=0;c<a.length;c++)if("showing"==a[c].mode)a:{b=P4(this.A.B,!0);for(var d=0;d<b.length;d++)if(b[d].toString()==a[c].id){b=b[d];break a}b=null}(this.loaded?this.o:null)!=b&&o5(this,b,!0)};
g.h.YX=function(){!this.o&&this.G||this.unload()};
g.h.WE=function(a,b,c,d){if(a){this.A.qF()&&(this.K=[],g.VT(this.L,"captions"),this.ca.Wj());var e=this.A;c=c||0;d=d||0;if(!g.v(a)){var f=new window.DataView(a);if(8<=f.byteLength&&1718909296==f.getUint32(4)&&(f=g.kK(f,1835295092),a=a.slice(f.dataOffset,f.dataOffset+f.size),!NDa(a)))if(e.F&&e.F.experiments.o("web_player_utf8_binary_captions_killswitch"))a=g.re(new window.Uint8Array(a));else{a=new window.Uint8Array(a);f=[];for(var k=0,l=0;k<a.length;){var m=a[k++];if(128>m)f[l++]=String.fromCharCode(m);
else if(191<m&&224>m){var n=a[k++];f[l++]=String.fromCharCode((m&31)<<6|n&63)}else if(239<m&&365>m){n=a[k++];var p=a[k++],t=a[k++];m=((m&7)<<18|(n&63)<<12|(p&63)<<6|t&63)-65536;f[l++]=String.fromCharCode(55296+(m>>10));f[l++]=String.fromCharCode(56320+(m&1023))}else n=a[k++],p=a[k++],f[l++]=String.fromCharCode((m&15)<<12|(n&63)<<6|p&63)}a=f.join("")}}if(a)try{if(g.v(a)){if("WEBVTT"==a.substring(0,6)){b=a;e.o||(e.o=new R4);var w=e.o.B(b,c);.01>Math.random()&&g.uE(Error("Deprecated subtitles format in web player: WebVTT"));
var z=w}else b:{w=a;var E=g.zs(w);if(!E||!E.firstChild)throw Error("Invalid caption track data: "+w);if("timedtext"==E.firstChild.tagName){if(3==(0,window.parseInt)(E.firstChild.getAttribute("format"),10)){e.o||(e.o=new G4(SDa(b),e.F));z=e.o.B(E,c);break b}throw Error("Unsupported subtitles format in web player: Format2");}if("transcript"==E.firstChild.tagName){e.o||(e.o=new E4(SDa(b)));var I=e.o.B(E,c);.05>Math.random()&&g.uE(Error("Deprecated subtitles format in web player: Format1"));z=I}else throw Error("Invalid caption track data: "+
w);}var N=z}else{z=a;w=d;if(!NDa(z))throw Error("Invalid binary caption track data");e.o||(e.o=new O4(w,b));N=e.o.B(z,c)}var K=N}catch(Qa){g.sE(Qa),e.o&&e.o.dispose(),e.o=null,K=[]}else K=[];g.RT(this.player,K);!this.M||this.Z||m5(this)||g.rN(this.B)||g.sN(this.B)||(g.Hu(this.ga),K=n4({kh:0,lg:5,gi:5,oj:2,textAlign:0,ci:0,lang:"fr"}),this.U=[K],e=["Cliquez sur "," pour acc\u00e9der aux param\u00e8tres."],this.ka||(N=new g.WH(g.zsa()),g.O(this,N),this.ka=N.element),N=K.end-K.start,(b=g.uI(this.o))&&
this.U.push(new k4(K.start,N,0,K.id,b)),this.U.push(new k4(K.start,N,0,K.id,e[0]),new k4(K.start,N,0,K.id,this.ka,!0),new k4(K.start,N,0,K.id,e[1],!0)),g.RT(this.player,this.U),g.Fu(this.ga));!this.M||this.Z||m5(this)||(n5(this,"module-enabled",!0),this.H&&(this.H.o=this.o),(K=g.Y(this.player.app))&&K.C&&g.dP(K.C.B));this.M=!1}};
g.h.zO=function(a){this.K.push(a);this.ca.Wj()};
g.h.AO=function(a){g.Sa(this.K,a);this.A instanceof a5&&this.A.J&&g.UT(this.player,[a]);this.ca.Wj()};
g.h.YW=function(a){if(a instanceof l4){var b=this.O[a.id];b&&b.D!=a&&(b.dispose(),delete this.O[a.id],b=null);b||(b=eEa(this,a))&&(this.O[a.id]=b)}else b=a.windowId,this.ba[b]||(this.ba[b]=[]),this.ba[b].push(a)};
g.h.fX=function(){fEa(this,this.U);this.U=null};
g.h.WG=function(){this.ca.stop();g.Yb(this.ba);this.K.sort(g.UP);var a=this.K;if(this.J){var b=(0,g.Yd)(a,function(a){return-1==this.J.indexOf(a)},this);
b.length&&(a=b)}(0,g.D)(a,this.YW,this);g.Gb(this.O,function(a,b){this.ba[b]?(a.element.parentNode||g.XT(this.player,a.element,4),a.lf(this.ba[b])):(a.dispose(),delete this.O[b])},this)};
g.h.JF=function(){g5(this,{},!0)};
g.h.Pt=function(){var a=p5.Jb;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.Cf?3:a.bold?1:a.Cf?2:0,textOpacity:a.textOpacity,windowColor:p5.windowColor,windowOpacity:p5.windowOpacity};var b=h5(this,"display-settings"),c;for(c in b)null!=b[c]&&(a[c]=b[c]);return a};
g.h.Hx=function(a,b){var c={};g.Da(c,h5(this,"display-settings"));g.Da(c,a);g5(this,c,b);this.player.V("captionssettingschanged")};
g.h.Ex=function(){!this.G&&this.loaded&&(g.Gb(this.O,function(a,b){a.dispose();delete this.O[b]},this),this.WG())};
g.h.kv=function(a,b){switch(a){case "fontSize":if((0,window.isNaN)(b))break;var c=g.md(b,-2,4);this.Hx({fontSizeIncrement:c});return c;case "reload":b&&!this.G&&o5(this,this.o,!0);break;case "stickyLoading":void 0!=b&&this.B.Lb&&n5(this,"module-enabled",!!b);break;case "track":if(!this.A)return{};if(b){if(this.G)break;if(!g.za(b))break;if(g.Xb(b)){o5(this,null,!0);break}var d;c=P4(this.A.B,!0);for(var e=0;e<c.length;e++){var f=c[e];f.A!=b.languageCode||d&&f.C!=b.languageName||(d=b.translationLanguage?
pDa(f,b.translationLanguage):f)}!d||d==this.o&&this.loaded||o5(this,d,!0)}else return this.loaded&&this.o&&!m5(this)?i4(this.o):{};return"";case "tracklist":return this.A?(0,g.J)(P4(this.A.B,!(!b||!b.includeAsr)),function(a){return i4(a)}):[];
case "translationLanguages":return this.A?this.A.H:[];case "displaySettings":d=this.Pt();if(g.rN(this.B)&&b&&g.za(b))if(b.reset)this.JF();else{f={};for(c in b)switch(c){case "color":case "background":case "windowColor":f[c]=hEa(b[c],d[c]);break;case "textOpacity":case "backgroundOpacity":case "windowOpacity":f[c]=iEa(b[c],d[c]);break;case "charEdgeStyle":var k=g.d1[b[c]];f[c]=g.sa(k)?k:d[c];break;case "fontSizeIncrement":f[c]=jEa(b[c],d[c]);break;case "fontFamilyOption":k=g.c1[b[c]];f.fontFamily=
g.sa(k)?k:d[c];break;case "fontStyle":k=g.e1[b[c]],f[c]=g.sa(k)?k:d[c]}for(e in f)f[e+"Override"]=!0;this.Hx(f,!0);d=this.Pt()}d.fontFamilyOption=g.aza[d.fontFamily];d.charEdgeStyle=g.bza[d.charEdgeStyle];d.fontStyle=g.cza[d.fontStyle];return d;case "sampleSubtitles":this.G||void 0==b||gEa(this,!!b);break;case "xmlTrack":b&&this.B.Lb&&(this.G||o5(this,new g.tI({languageName:b.name}),!1,b.xml))}};
g.h.xO=function(){var a="reload fontSize track tracklist translationLanguages displaySettings sampleSubtitle".split(" ");this.B.Lb&&a.push("stickyLoading","xmlTrack");return a};
g.h.yO=function(){var a=this.o;return a?{cc:a.F}:{}};
g.h.LG=function(){this.loaded&&this.o&&!m5(this)?(n5(this,"module-enabled",!1),this.unload(),j5(this,!0)&&o5(this,k5(this),!1)):o5(this,m5(this)?l5(this,!0):this.o,!0)};
g.h.oS=function(){var a=m5(this);j5(this,a)?o5(this,this.player.getAudioTrack().kp,!1):this.D.captionTracks.length&&(this.loaded&&this.unload(),this.FC()&&(a?o5(this,l5(this),!1):this.load()))};g.hX.captions=i5;})(_yt_player);
