(function(g){var window=this;var r5=function(a,b,c){var d=b.Oa();g.U(a.element,"ytp-suggestion-set",!!d.videoId);var e=b.getPlaylistId();c=b.kd(c?c:"mqdefault.jpg");var f=b instanceof g.FO&&b.lengthSeconds?g.JU(b.lengthSeconds):null,k=!!e;e=k&&"RD"==(new g.WP(e.substr(0,2),e.substr(2))).type;var l=b instanceof g.FO?b.Ea:null;d={title:b.title,author:b.author,author_and_views:d.shortViewCount?b.author+" \u2022 "+d.shortViewCount:b.author,aria_label:b.vl||g.zU("Regarder $TITLE",{TITLE:b.title}),duration:f,url:b.hm(),is_live:l,is_list:k,
is_mix:e,background:c?"background-image: url("+c+")":""};b instanceof g.YP&&(d.playlist_length=b.getLength());a.update(d)},s5=function(a,b){g.bI.call(this,{I:"div",
ea:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.player=a;this.created=!1},t5=function(a){g.V.call(this,{I:"div",
N:"ytp-upnext",T:{"aria-label":"{{aria_label}}"},P:[{I:"div",N:"ytp-cued-thumbnail-overlay-image",T:{style:"{{background}}"}},{I:"span",N:"ytp-upnext-top",P:[{I:"span",N:"ytp-upnext-header",da:"\u00c0 suivre"},{I:"span",N:"ytp-upnext-title",da:"{{title}}"},{I:"span",N:"ytp-upnext-author",da:"{{author}}"}]},{I:"a",N:"ytp-upnext-autoplay-icon",T:{role:"button",href:"{{url}}","aria-label":"Lire la vid\u00e9o suivante"},P:[{I:"svg",T:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},P:[{I:"circle",
N:"ytp-svg-autoplay-circle",T:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{I:"circle",N:"ytp-svg-autoplay-ring",T:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{I:"path",N:"ytp-svg-fill",T:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{I:"span",N:"ytp-upnext-bottom",P:[{I:"span",N:"ytp-upnext-cancel"},{I:"span",N:"ytp-upnext-paused",da:"La lecture automatique est d\u00e9sactiv\u00e9e"}]}]});
this.F=null;var b=this.o["ytp-upnext-cancel"];this.F=new g.V({I:"button",ea:["ytp-upnext-cancel-button","ytp-button"],T:{tabindex:"0","aria-label":"Annuler la lecture automatique"},da:"Annuler"});g.O(this,this.F);this.F.W("click",this.wS,this);this.F.xa(b);this.B=a;this.L=this.o["ytp-svg-autoplay-ring"];this.H=this.G=this.C=this.D=null;this.J=new g.Eu(this.Mo,5E3,this);g.O(this,this.J);this.K=0;this.R(this.o["ytp-upnext-autoplay-icon"],"click",this.HU);this.jE();this.R(a,"autonavvisibility",this.jE);
this.R(a,"mdxnowautoplaying",this.VT);this.R(a,"mdxautoplaycanceled",this.XT);this.R(a,"mdxautoplayupnext",this.ZG);3==this.B.Sa()&&(a=(a=g.GT(g.AT(this.B)))?a.rL():null)&&this.ZG(a)},u5=function(a,b){if(!a.C){g.wG("a11y-announce","\u00c0 suivre "+a.D.title);
a.K=g.GG();a.C=new g.Eu((0,g.B)(a.Bs,a,b),25);a.Bs(b);var c=b||g.X(a.B).experiments.A("autoplay_time")||1E4;a.B.ya("onAutonavCoundownStarted",c)}g.Qq(a.element,"ytp-upnext-autoplay-paused")},w5=function(a){v5(a);
a.K=g.GG();a.Bs();g.T(a.element,"ytp-upnext-autoplay-paused")},v5=function(a){a.C&&(a.C.dispose(),a.C=null)},x5=function(a,b){b=void 0===b?!1:b;
if(g.X(a.B).experiments.o("autonav_notifications")&&b&&window.Notification&&window.document.hasFocus){var c=window.Notification.permission;"default"==c?window.Notification.requestPermission():"granted"!=c||window.document.hasFocus()||(c=a.D.Oa(),a.Mo(),a.G=new window.Notification("\u00c0 suivre",{body:c.title,icon:c.kd()}),a.H=a.R(a.G,"click",a.xU),a.J.start())}v5(a);a.B.Bk(!1,b)},oEa=function(a){s5.call(this,a,"subscribecard-endscreen");
var b=a.getVideoData();this.B=new g.V({I:"div",N:"ytp-subscribe-card",P:[{I:"img",N:"ytp-author-image",T:{src:b.profilePicture}},{I:"div",N:"ytp-subscribe-card-right",P:[{I:"div",N:"ytp-author-name",da:b.author},{I:"div",N:"html5-subscribe-button-container"}]}]});g.O(this,this.B);this.B.xa(this.element);this.C=new g.sZ("S'abonner",null,"Se d\u00e9sabonner",null,!0,!1,b.il,b.subscribed,"trailer-endscreen",null,null,a);g.O(this,this.C);this.C.xa(this.B.o["html5-subscribe-button-container"]);this.hide()},
y5=function(a){var b=g.X(a),c=g.PI||g.rf?{style:"will-change: opacity"}:void 0,d=b.o,e=["ytp-videowall-still"];
b.A&&e.push("ytp-videowall-show-text");g.V.call(this,{I:"a",ea:e,T:{href:"{{url}}",target:d?"_blank":"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},P:[{I:"div",N:"ytp-videowall-still-image",T:{style:"{{background}}"}},{I:"span",N:"ytp-videowall-still-info",P:[{I:"span",N:"ytp-videowall-still-info-bg",P:[{I:"span",N:"ytp-videowall-still-info-content",T:c,P:[{I:"span",N:"ytp-videowall-still-info-title",da:"{{title}}"},{I:"span",
N:"ytp-videowall-still-info-author",da:"{{author_and_views}}"},{I:"span",N:"ytp-videowall-still-info-live",da:"En direct"},{I:"span",N:"ytp-videowall-still-info-duration",da:"{{duration}}"}]}]}]},{I:"span",ea:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],P:[{I:"span",N:"ytp-videowall-still-listlabel-icon"},"Playlist",{I:"span",N:"ytp-videowall-still-listlabel-length",P:[" (",{I:"span",da:"{{playlist_length}}"},")"]}]},{I:"span",ea:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],
P:[{I:"span",N:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{I:"span",N:"ytp-videowall-still-listlabel-length",da:" (50+)"}]}]});this.F=d;this.B=a;this.C=null;this.D=new g.dG(this);g.O(this,this.D);this.W("click",this.H);this.W("keypress",this.J);this.D.R(a,"videodatachange",this.G);g.X(a).U&&(a=a.app.la,b=this.element,g.Ma(a.o,b),g.Pa(a.o,b),c=String(a.K++),b.setAttribute("data-visual-id",c),g.mf(this,(0,g.B)(a.J,a,b)));this.G()},z5=function(a){s5.call(this,a,"videowall-endscreen");
this.K=a;this.G=0;this.C=[];this.H=this.D=this.F=null;this.J=this.U=!1;this.O=null;this.Y=new g.dG(this);g.O(this,this.Y);this.L=new g.Eu(g.Ca(g.T,this.element,"ytp-show-tiles"),0);g.O(this,this.L);var b=new g.V({I:"button",ea:["ytp-button","ytp-endscreen-previous"],T:{"aria-label":"Pr\u00e9c\u00e9dente"},P:[g.CU()]});g.O(this,b);b.xa(this.element);b.W("click",this.rQ,this);this.M=new g.WH({I:"div",N:"ytp-endscreen-content"});g.O(this,this.M);this.M.xa(this.element);b=new g.V({I:"button",ea:["ytp-button",
"ytp-endscreen-next"],T:{"aria-label":"Suivante"},P:[g.DU()]});g.O(this,b);b.xa(this.element);b.W("click",this.qQ,this);this.B=new t5(a);g.O(this,this.B);g.XT(this.player,this.B.element,4);this.hide()},A5=function(a){return g.aU(a.player)&&a.Dz()&&!a.H},pEa=function(a,b){return(0,g.J)(b.suggestions,function(b){b=g.mX(g.X(a.K),b);
g.O(a,b);return b})},B5=function(a){var b=a.Jv();
b!=a.U&&(a.U=b,a.player.V("autonavvisibility"))},C5=function(a){g.iU.call(this,a);
this.o=null;this.A=new g.dG(this);g.O(this,this.A);this.B=g.X(a);qEa(a)?this.o=new z5(this.player):this.B.Ja?this.o=new oEa(this.player):this.o=new s5(this.player);g.O(this,this.o);g.XT(this.player,this.o.element,4);this.IF();this.A.R(a,"videodatachange",this.IF,this);this.A.R(a,g.VP("endscreen"),this.pO,this);this.A.R(a,"crx_endscreen",this.qO,this)},qEa=function(a){a=g.X(a);
return a.Da&&!a.Ja};
g.r(s5,g.bI);s5.prototype.create=function(){this.created=!0};
s5.prototype.destroy=function(){this.created=!1};
s5.prototype.Dz=function(){return!1};
s5.prototype.Jv=function(){return!1};g.r(t5,g.V);g.h=t5.prototype;g.h.Mo=function(){this.G&&(this.J.stop(),this.Ka(this.H),this.H=null,this.G.close(),this.G=null)};
g.h.jE=function(){g.aI(this,g.BT(this.B))};
g.h.xU=function(){window.focus();this.Mo()};
g.h.hide=function(){g.V.prototype.hide.call(this)};
g.h.Bs=function(a){a=a||g.X(this.B).experiments.A("autoplay_time")||1E4;var b=Math.min(g.GG()-this.K,a);a=Math.min(b/a,1);this.L.setAttribute("stroke-dashoffset",-211*(a+1));1<=a&&3!=this.B.Sa()?x5(this,!0):this.C&&this.C.start()};
g.h.HU=function(a){!g.ce(this.F.element,g.SF(a))&&g.mW(a,this.B)&&x5(this)};
g.h.wS=function(){g.DT(this.B,!0)};
g.h.VT=function(a){this.B.Sa();this.show();u5(this,a)};
g.h.ZG=function(a){this.B.Sa();this.D&&this.D.Oa().videoId==a.Oa().videoId||(this.D=a,r5(this,a,"hqdefault.jpg"))};
g.h.XT=function(){this.B.Sa();v5(this);this.hide()};
g.h.X=function(){v5(this);this.Mo();g.V.prototype.X.call(this)};g.r(oEa,s5);g.r(y5,g.V);y5.prototype.Uk=function(){g.dU(this.B,this.element);var a=this.C.Oa().videoId,b=this.C.getPlaylistId();g.P_(this.B.app,a,this.C.Kd,b,void 0,void 0,void 0)};
y5.prototype.H=function(a){g.mW(a,this.B,this.F,this.C.Kd||void 0)&&this.Uk()};
y5.prototype.J=function(a){switch(a.keyCode){case 13:case 32:g.XF(a)||(this.Uk(),g.WF(a))}};
y5.prototype.G=function(){var a=this.B.getVideoData(),b=g.X(this.B);this.F=a.isDni?!1:b.o};g.r(z5,s5);g.h=z5.prototype;g.h.create=function(){s5.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.F=pEa(this,a),this.D=a);this.Ug();this.Y.R(this.player,"appresize",this.Ug);this.Y.R(this.player,"onVideoAreaChange",this.Ug);this.Y.R(this.player,"videodatachange",this.sQ);this.Y.R(this.player,"autonavchange",this.Kv);this.Y.R(this.player,"autonavcancel",this.pQ);a=this.D.autonavState;a!=this.O&&this.Kv(a);this.Y.R(this.element,"transitionend",this.aW)};
g.h.destroy=function(){g.fG(this.Y);g.of(this.C);this.C=[];this.F=null;s5.prototype.destroy.call(this);g.Qq(this.element,"ytp-show-tiles");this.L.stop();this.O=this.D.autonavState};
g.h.Dz=function(){return 1!=this.D.autonavState};
g.h.show=function(){s5.prototype.show.call(this);g.Qq(this.element,"ytp-show-tiles");g.X(this.player).A?g.Gu(this.L):this.L.start();(this.J||this.H&&this.H!=this.D.clientPlaybackNonce)&&g.DT(this.player,!1);A5(this)?(B5(this),2==this.D.autonavState?g.X(this.player).experiments.o("fast_autonav_in_background")&&3==this.player.cj()?x5(this.B,!0):u5(this.B):3==this.D.autonavState&&w5(this.B)):(g.DT(this.player,!0),B5(this))};
g.h.hide=function(){s5.prototype.hide.call(this);w5(this.B);B5(this)};
g.h.aW=function(a){g.SF(a)==this.element&&this.Ug()};
g.h.Ug=function(){if(this.F&&this.F.length){g.T(this.element,"ytp-endscreen-paginate");var a=g.OT(this.K,!0),b=g.qI(this.K);b&&(b=b.nd()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.F.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var p=b/2,t=e/2,w=b<=f-2&&n>=t*m,z=e<=k-2&&n>=p*m;if((p+1)/t*d/c>c/(p/(t+1)*d)&&z)n-=p*m,e+=2;else if(w)n-=t*m,b+=2;else if(z)n-=p*m,e+=2;else break}d=
!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;m*=g.md(a.width/m||1,1,1.21);n*=g.md(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.M.element;g.Qh(a,m,n);g.yh(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});c=this.B;f=this.F[0];c.D=f;r5(c,f,"hqdefault.jpg");g.U(this.element,"ytp-endscreen-takeover",A5(this));B5(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(k=0;k<e;k++)if(p=c,t=0,d&&f>=b-2&&k>=e-
2?t=1:0==k%2&&0==f%2&&(2>k&&2>f?0==k&&0==f&&(t=2):t=2),p=g.nd(p+this.G,l),0!=t){w=this.C[c];w||(w=new y5(this.player),this.C[c]=w,a.appendChild(w.element));z=Math.floor(n*k/e);var E=Math.floor(m*f/b),I=Math.floor(n*(k+t)/e)-z-4,N=Math.floor(m*(f+t)/b)-E-4;g.Fh(w.element,E,z);g.Qh(w.element,N,I);g.yh(w.element,"transitionDelay",(k+f)/20+"s");g.U(w.element,"ytp-videowall-still-mini",1==t);g.U(w.element,"ytp-videowall-still-large",2<t);t=w;p=this.F[p];t.C!=p&&(t.C=p,r5(t,p,g.Oq(t.element,"ytp-videowall-still-large")?
"hqdefault.jpg":"mqdefault.jpg"),w=(p=p.Kd)&&p.itct)&&(p=t.B,g.X(p).U&&(p=p.app.la,t=t.element,z=t.getAttribute("data-visual-id"),g.Ma(p.o,t),p.A?w&&(t.visualElement=g.eH(w)):g.bU(p,"onLogServerVeCreated",{id:z,tracking_params:w})));c++}g.U(this.element,"ytp-endscreen-paginate",c<l);for(b=this.C.length-1;b>=c;b--)e=this.C[b],g.Xd(e.element),g.nf(e);this.C.length=c}};
g.h.sQ=function(){var a=this.player.getVideoData();this.D!=a&&(this.G=0,this.F=pEa(this,a),this.D=a,this.Ug())};
g.h.qQ=function(){this.G+=this.C.length;this.Ug()};
g.h.rQ=function(){this.G-=this.C.length;this.Ug()};
g.h.sN=function(){return!!this.B.C};
g.h.Kv=function(a){1==a?(this.J=!1,this.H=this.D.clientPlaybackNonce,v5(this.B),this.A&&this.Ug()):(this.J=!0,this.A&&A5(this)&&(2==a?u5(this.B):3==a&&w5(this.B)))};
g.h.pQ=function(a){if(a){for(a=0;a<this.C.length;a++)g.eU(this.K,this.C[a].element,!0);this.Kv(1)}else this.H=null,this.J=!1;this.Ug()};
g.h.Jv=function(){return this.A&&A5(this)};g.r(C5,g.iU);g.h=C5.prototype;g.h.EC=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!qEa(this.player)||b;a=g.VO(a,"ypc_module");var c=g.r_(this.player.app);return b&&!a&&!c};
g.h.DC=function(){return this.o.Jv()};
g.h.oN=function(){return this.DC()?this.o.sN():!1};
g.h.X=function(){g.VT(this.player,"endscreen");g.iU.prototype.X.call(this)};
g.h.load=function(){g.iU.prototype.load.call(this);this.o.show()};
g.h.unload=function(){g.iU.prototype.unload.call(this);this.o.hide();this.o.destroy()};
g.h.pO=function(a){this.EC()&&(this.o.created||this.o.create(),"load"==a.getId()&&this.load())};
g.h.qO=function(a){"load"==a.getId()&&this.loaded&&this.unload()};
g.h.IF=function(){g.VT(this.player,"endscreen");var a=Math.max(1E3*(this.player.getVideoData().lengthSeconds-10),0);a=new g.TP(a,0x8000000000000,{id:"preload",namespace:"endscreen"});g.O(this,a);var b=new g.TP(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.O(this,b);g.RT(this.player,[a,b])};g.hX.endscreen=C5;})(_yt_player);
